### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Celggar** [framgia/android-emulator-detector#17]
Just not working
<img width="1129" alt="screen shot 2017-03-17 at 1 39 52 pm" src="https://cloud.githubusercontent.com/assets/6495830/24057960/5d558706-0b17-11e7-9e89-ee0c821e95a0.png">
<img width="1129" alt="screen shot 2017-03-17 at 1 41 33 pm" src="https://cloud.githubusercontent.com/assets/6495830/24057982/75756e78-0b17-11e7-8454-ba7d49c4496c.png">

**Comment by KaKaVip** [comment]
@Ceaggar Thank you, we'll checking..!

**Comment by yubo725** [comment]
haha~this is yeshen emulator~

**Comment by HamzehSoboh** [comment]
Any updates please?

**Comment by HuiminPyo** [comment]
Is there any solution

**Comment by serralove** [comment]
private EmulatorDetector(Context pContext) {
        mContext = pContext;
        mListPackageName.add("com.google.android.launcher.layouts.genymotion");
        mListPackageName.add("com.bluestacks");
        mListPackageName.add("com.bignox.app");
        mListPackageName.add("com.vphone.launcher");
    }

**Comment by HuiminPyo** [comment]
@serralove I tested and only "com.vphone.launcher" detected Nox(latest 1.2.1.0)
Thank you

**Comment by HamzehSoboh** [comment]
@HuiminPyo but be careful, that package can be downloaded from [googleplay](https://play.google.com/store/apps/details?id=com.vphone.launcher) although it seems poor, but just to take in mind.

**Comment by HuiminPyo** [comment]
@HamzehSoboh  Thank you :)

**Comment by knoxcard** [comment]
@Ceaggar - close ticket?

**Comment by Celggar** [comment]
Thanks so much!
